# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b8ec53556362d8ae3e0b5b7c7f0202d151213bfac57468603b7ea7a8a7d66b3d7278efda18d72c1e1dd3bc0335d29f6c5faf3027e9eaadfc49a77015e8e18ec

test:
  secret_key_base: 2f863493c96cf0542a486dfde6fa8fbfd89c6a20103730734a2b70a38f4aab83e1317dbd26d9526a803532df2fbf8c14c536343f3991c594ba4d89fa34d4a416

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
